"""add category to applications

Revision ID: 4d4a3427cd1f
Revises: e1b7d2995edc
Create Date: 2026-04-16 22:44:17.778220

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4d4a3427cd1f'
down_revision: Union[str, Sequence[str], None] = 'e1b7d2995edc'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('applications', sa.Column('category', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('applications', 'category')
    # ### end Alembic commands ###
