"""add received_at to email_events

Revision ID: c198cb0bdb5a
Revises: 4d4a3427cd1f
Create Date: 2026-04-21 11:42:53.803508

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c198cb0bdb5a'
down_revision: Union[str, Sequence[str], None] = '4d4a3427cd1f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('email_events', sa.Column('received_at', sa.DateTime(timezone=True), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('email_events', 'received_at')
    # ### end Alembic commands ###
